# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simulador_Spreeta.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import icons_


BTNSTYLE = """QPushButton{background-color: rgb(255, 255, 255); color:rgb(0,0,0)}
                QPushButton::Hover{background-color: rgb(50, 160, 255); }"""

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1034, 683)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.main_frame = QtWidgets.QFrame(Form)
        self.main_frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 90, 150);\n"
"}\n"
"QLabel{\n"
"    border: none;\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 15)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_config = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_config.sizePolicy().hasHeightForWidth())
        self.frame_config.setSizePolicy(sizePolicy)
        self.frame_config.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_config.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_config.setStyleSheet("QFrame{\n"
                                        "    background-color: rgb(0, 90, 150);\n"
                                        "    border: 2px solid;\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    border-color: rgb(0, 90, 150);\n"
                                        "    border-radius: 10px;    \n"
                                        "}\n"
                                        "QLabel{\n"
                                        "    border: none;\n"
                                        "}\n"
                                        "")
        self.frame_config.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_config.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_config.setObjectName("frame_config")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_config)
        self.verticalLayout_2.setContentsMargins(15, 15, 10, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gb_calibration = QtWidgets.QGroupBox(self.frame_config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_calibration.sizePolicy().hasHeightForWidth())
        self.gb_calibration.setSizePolicy(sizePolicy)
        self.gb_calibration.setStyleSheet("font: 600 10pt  \"Segoe UI\";"   "color: rgb(255, 255, 255);\n")
        self.gb_calibration.setObjectName("gb_calibration")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gb_calibration)
        self.gridLayout_8.setSpacing(10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btn_Wet_flow_cell = QtWidgets.QPushButton(self.gb_calibration)
        self.btn_Wet_flow_cell.setObjectName("btn_Wet_flow_cell")
        self.btn_Wet_flow_cell.setStyleSheet(BTNSTYLE)
        self.gridLayout_8.addWidget(self.btn_Wet_flow_cell, 3, 0, 1, 1)
        self.btn_Dry_flow_cell = QtWidgets.QPushButton(self.gb_calibration)
        self.btn_Dry_flow_cell.setObjectName("btn_Dry_flow_cell")
        self.btn_Dry_flow_cell.setStyleSheet(BTNSTYLE)
        self.gridLayout_8.addWidget(self.btn_Dry_flow_cell, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gb_calibration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setStyleSheet("")
        self.label_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.pgsBar_wet_cell = QtWidgets.QProgressBar(self.gb_calibration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pgsBar_wet_cell.sizePolicy().hasHeightForWidth())
        
        self.pgsBar_wet_cell.setSizePolicy(sizePolicy)
        self.pgsBar_wet_cell.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pgsBar_wet_cell.setProperty("value", 2)
        self.pgsBar_wet_cell.setTextVisible(False)
        self.pgsBar_wet_cell.setStyleSheet("""QProgressBar{
                                                border: solid grey;
                                                border-radius: 15px;
                                                color: black;
                                                }"""
                                        "QProgressBar::chunk{ "
                                           "   background-color:  #239b56 ;"
                                           "     border-radius :15px;"
                                           "    }  ")
        self.pgsBar_wet_cell.setObjectName("pgsBar_wet_cell")
        self.gridLayout_8.addWidget(self.pgsBar_wet_cell, 3, 1, 1, 1)
        
        self.pgsBar_dry_cell = QtWidgets.QProgressBar(self.gb_calibration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pgsBar_dry_cell.sizePolicy().hasHeightForWidth())
        self.pgsBar_dry_cell.setSizePolicy(sizePolicy)
        self.pgsBar_dry_cell.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pgsBar_dry_cell.setProperty("value", 2)
        self.pgsBar_dry_cell.setObjectName("pgsBar_dry_cell")
        self.pgsBar_dry_cell.setTextVisible(False)
        self.pgsBar_dry_cell.setStyleSheet("""QProgressBar{
                                                border: solid grey;
                                                border-radius: 15px;
                                                color: black;
                                                }"""
                                        "QProgressBar::chunk{ "
                                           "   background-color:  #239b56 ;"
                                           "     border-radius :15px;"
                                           "    }  ")
        self.gridLayout_8.addWidget(self.pgsBar_dry_cell, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gb_calibration)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        
        self.gb_controls = QtWidgets.QGroupBox(self.frame_config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_controls.sizePolicy().hasHeightForWidth())
        self.gb_controls.setSizePolicy(sizePolicy)
        self.gb_controls.setStyleSheet("font: 600 10pt  \"Segoe UI\";" "color: rgb(255, 255, 255);\n")
        self.gb_controls.setObjectName("gb_controls")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gb_controls)
        self.gridLayout_9.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout_9.setSpacing(10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btn_start = QtWidgets.QPushButton(self.gb_controls)
        self.btn_start.setObjectName("btn_start")
        self.btn_start.setStyleSheet(BTNSTYLE)
        self.gridLayout_9.addWidget(self.btn_start, 0, 0, 1, 1)
        self.btn_save = QtWidgets.QPushButton(self.gb_controls)
        self.btn_save.setObjectName("btn_save")
        self.btn_save.setStyleSheet(BTNSTYLE)
        self.gridLayout_9.addWidget(self.btn_save, 1, 1, 1, 1)
        self.btn_reset = QtWidgets.QPushButton(self.gb_controls)
        self.btn_reset.setObjectName("btn_reset")
        self.btn_reset.setStyleSheet(BTNSTYLE)
        self.gridLayout_9.addWidget(self.btn_reset, 0, 1, 1, 1)
        self.btn_stop = QtWidgets.QPushButton(self.gb_controls)
        self.btn_stop.setObjectName("btn_stop")
        self.btn_stop.setStyleSheet(BTNSTYLE)
        self.gridLayout_9.addWidget(self.btn_stop, 1, 0, 1, 1)
        self.btn_view_data = QtWidgets.QCommandLinkButton(self.gb_controls)
        self.btn_view_data.setObjectName("btn_view_data")
        self.btn_view_data.setStyleSheet(BTNSTYLE)
        self.gridLayout_9.addWidget(self.btn_view_data, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.gb_controls)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gb_Results = QtWidgets.QGroupBox(self.frame_config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_Results.sizePolicy().hasHeightForWidth())
        self.gb_Results.setSizePolicy(sizePolicy)
        self.gb_Results.setStyleSheet("font: 600 10pt \"Segoe UI\";\n ""color: rgb(255, 255, 255);")
        self.gb_Results.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gb_Results.setObjectName("gb_Results")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gb_Results)
        self.gridLayout_7.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout_7.setSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_13 = QtWidgets.QLabel(self.gb_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.min_pixel = QtWidgets.QLineEdit(self.gb_Results)
        self.min_pixel.setReadOnly(True)
        self.min_pixel.setObjectName("min_pixel")
        self.gridLayout_7.addWidget(self.min_pixel, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gb_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 1, 0, 1, 1)
        self.resonance_angle = QtWidgets.QLineEdit(self.gb_Results)
        self.resonance_angle.setText("")
        self.resonance_angle.setReadOnly(True)
        self.resonance_angle.setObjectName("resonance_angle")
        self.gridLayout_7.addWidget(self.resonance_angle, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gb_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 2, 0, 1, 1)
        self.refractive_index = QtWidgets.QLineEdit(self.gb_Results)
        self.refractive_index.setText("")
        self.refractive_index.setReadOnly(True)
        self.refractive_index.setObjectName("refractive_index")
        self.gridLayout_7.addWidget(self.refractive_index, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gb_Results)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.frame_config)
        self.frame_graphs = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_graphs.sizePolicy().hasHeightForWidth())
        self.frame_graphs.setSizePolicy(sizePolicy)
        self.frame_graphs.setStyleSheet("")
        self.frame_graphs.setObjectName("frame_graphs")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_graphs)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_Sensorgram = QtWidgets.QFrame(self.frame_graphs)
        self.frame_Sensorgram.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid;\n"
"    border-color: rgb(0, 90, 150);\n"
"    border-radius: 10px;    \n"
"}\n"
"QLabel{\n"
"    border: none;\n"
"}\n"
"")
        self.frame_Sensorgram.setObjectName("frame_Sensorgram")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_Sensorgram)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.frame_Sensorgram)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_Sensorgram)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(35, 25))
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icons/icons/LOGO.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.btn_add_label = QtWidgets.QPushButton(self.frame_Sensorgram)
        self.btn_add_label.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_add_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_add_label.setStyleSheet("font: 600 10pt  \"Segoe UI\";")
        self.btn_add_label.setObjectName("btn_add_label")
        self.gridLayout_3.addWidget(self.btn_add_label, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_Sensorgram, 2, 1, 1, 1)
        self.frame_SPR_curve = QtWidgets.QFrame(self.frame_graphs)
        self.frame_SPR_curve.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid;\n"
"    border-color: rgb(0, 90, 150);\n"
"    border-radius: 10px;    \n"
"}\n"
"QLabel{\n"
"    border: none;\n"
"}\n"
"")
        self.frame_SPR_curve.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SPR_curve.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SPR_curve.setObjectName("frame_SPR_curve")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_SPR_curve)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_SPR_curve)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(35, 25))
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/icons/LOGO.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_SPR_curve)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_SPR_curve, 0, 1, 1, 1)
        self.frame_Raw_signal = QtWidgets.QFrame(self.frame_graphs)
        self.frame_Raw_signal.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid;\n"
"    border-color: rgb(0, 90, 150);\n"
"    border-radius: 10px;    \n"
"}\n"
"QLabel{\n"
"    border: none;\n"
"}\n"
"")
        self.frame_Raw_signal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Raw_signal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Raw_signal.setObjectName("frame_Raw_signal")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_Raw_signal)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame_Raw_signal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(35, 25))
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/icons/icons/LOGO.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_Raw_signal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_5.addLayout(self.verticalLayout_4, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.frame_Raw_signal, 2, 0, 1, 1)
        self.frame_Sample = QtWidgets.QFrame(self.frame_graphs)
        self.frame_Sample.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid;\n"
"    border-color: rgb(0, 90, 150);\n"
"    border-radius: 10px;    \n"
"}\n"
"QLabel{\n"
"    border: none;\n"
"}\n"
"")
        self.frame_Sample.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Sample.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Sample.setObjectName("frame_Sample")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_Sample)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_Sample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(35, 25))
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/icons/LOGO.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 0, 1, 4)
        self.cbox_channel = QtWidgets.QComboBox(self.frame_Sample)
        self.cbox_channel.setStyleSheet("font: 600 11pt \"Segoe UI\";")
        self.cbox_channel.setObjectName("cbox_channel")
        self.cbox_channel.addItem("")
        self.cbox_channel.addItem("")
        self.cbox_channel.addItem("")
        self.gridLayout_2.addWidget(self.cbox_channel, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_Sample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.label_4.setMaximumWidth(205)
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.frame_Sample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 1, 1, 2)
        self.gridLayout.addWidget(self.frame_Sample, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_graphs)
        self.verticalLayout_6.addWidget(self.main_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.gb_calibration.setTitle(_translate("Form", "Calibration"))
        self.btn_Wet_flow_cell.setText(_translate("Form", "Wet flow cell"))
        self.btn_Dry_flow_cell.setText(_translate("Form", "Dry flow cell"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Calibrate Sensor</span></p></body></html>"))
        self.gb_controls.setTitle(_translate("Form", "Controls"))
        self.btn_start.setText(_translate("Form", "Start monitoring"))
        self.btn_save.setText(_translate("Form", "Save data"))
        self.btn_reset.setText(_translate("Form", "Reset"))
        self.btn_stop.setText(_translate("Form", "Stop monitoring"))
        self.btn_view_data.setText(_translate("Form", "View data"))
        self.gb_Results.setTitle(_translate("Form", "Results"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Min pixel:</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Resonace angle:</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Refractive index:</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:700;\">Sensorgram: </span><span style=\" font-size:11pt;\">Refractive index</span></p></body></html>"))
        self.btn_add_label.setText(_translate("Form", "Add Label"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:700;\">SPR Curve: </span><span style=\" font-size:11pt;\">Processed</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:700;\">Raw signal</span></p></body></html>"))
        self.cbox_channel.setItemText(0, _translate("Form", "Channel #1"))
        self.cbox_channel.setItemText(1, _translate("Form", "Channel #2"))
        self.cbox_channel.setItemText(2, _translate("Form", "Channel #3"))
        self.label_4.setText(_translate("Form", u"<html><head/><body><p><span style=\" font-size:11pt; font-weight:700;\">Sample: </span><span style=\" font-size:11pt;\">Reflectancia vs. Angle</span></p></body></html>", None))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:700;\">Channel:</span></p></body></html>"))

